### ISSUE TITLE
ios5 style with a big label

### ISSUE THREAD

**Issue by sarbogast** [naeka/jquery-switchbutton#1]
Thanks a lot for your component, it's very useful. It just has a little bug when you use a big label is ios5 style:

http://oi41.tinypic.com/1222mnq.jpg

http://oi39.tinypic.com/23kunir.jpg

**Comment by leo-naeka** [comment]
Hi,
Thanks for your interest in the plugin and for your report.
I suppose that I have fixed the bug you were encountering.
Keep me informed in case of trouble.
